
services:
  db:
      image: mysql:8
      restart: always
      environment:
        MYSQL_DATABASE: blind-test
        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        MYSQL_USER: ${MYSQL_USER}
        MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      ports:
        - "3325:3306"